name: Delete All Files

on:
  workflow_dispatch:   # تشغيل يدوي

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove all files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git rm -r --cached .
          git commit -m "Delete all files" --allow-empty
          git push
