name: Remove all files
run: |
  git config user.name "github-actions"
  git config user.email "actions@github.com"
  git checkout main
  git fetch --unshallow --tags
  rm -rf ./* .[^.]* 2>/dev/null || true
  git add -A
  git commit -m "Delete all files" --allow-empty
  git push origin main --force
